---
name: Lint & Security Scan

on: [push, pull_request]

jobs:
  lint-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
